version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   resource_class: large
   steps:
      - run:
          command: |
           git config --global user.name "venom-stark"
           git config --global user.email "sachidanandabehera562@gmail.com"
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/kramel.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
